theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false
  seo:
    title:
      separator: "•"
  logo:
    header: "/assets/images/logo-black-on-white.svg"
    footer: "/assets/images/logo-black.svg"